### ISSUE TITLE
Using API?

### ISSUE THREAD

**Issue by EdibleMuffin** [Rorical/Pixivel-Frontend#3]
Can I have permission to use your api by doing a reverse proxy? unless you have api available for open source

**Comment by Rorical** [comment]
We are about to release the next version of Pixivel with open-sourced backend and frontend. This old version API is archived and will no longer be used. When the new version backend is complete I will make it public. I strongly suggest you wait and use the newest backend. If you want to use the current old API, please dm me so I can disable Cloudflare WAF for your server.
